version: "3.4"

services:
  ########################################################
  # FRONTEND #############################################
  ########################################################
  frontend:
    image: gradido/frontend:development
    build:
      target: development
    environment:
      - NODE_ENV="development"
      # - DEBUG=true
      - NUXT_BUILD=/tmp/nuxt # avoid file permission issues when `rm -rf .nuxt/`
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      - frontend_node_modules:/app/node_modules
      # bind the local folder to the docker to allow live reload
      - ./frontend:/app

  ########################################################
  # BACKEND ##############################################
  ########################################################
  #backend:
  #  image: ocelotsocialnetwork/backend:development
  #  build:
  #    target: development
  #  environment:
  #    - NODE_ENV="development"
  #    - DEBUG=true
  #  volumes:
  #    # This makes sure the docker container has its own node modules.
  #    # Therefore it is possible to have a different node version on the host machine
  #    - backend_node_modules:/app/node_modules
  #    # bind the local folder to the docker to allow live reload
  #    - ./backend:/app

   
volumes:
  frontend_node_modules:
  # backend_node_modules: