version: "3.4"

services:

  ########################################################
  # BACKEND ##############################################
  ########################################################
  backend:
    image: gradido/backend:test
    build:
      target: test
    networks:
      - external-net
      - internal-net
    environment:
      - NODE_ENV="test"
      - DB_HOST=mariadb

  ########################################################
  # DATABASE #############################################
  ########################################################
  database:
    build:
      context: ./database
      target: test_up
  #  restart: always # this is very dangerous, but worth a test for the delayed mariadb startup at first run

  #########################################################
  ## MARIADB ##############################################
  #########################################################
  mariadb:
    networks: 
      - internal-net
      - external-net
    volumes: 
      - db_test_vol:/var/lib/mysql

  #########################################################
  ## COMMUNITY SERVER (cakephp with php-fpm) ##############
  #########################################################
  community-server:
    build: 
      context: .
      target: test
      dockerfile: ./community_server/Dockerfile
    depends_on: 
      - mariadb
    networks: 
      - internal-net
    volumes:
      - ./community_server/config/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - ./community_server/src:/var/www/cakephp/src
      - ./coverage/community:/var/www/cakephp/webroot/coverage

        
  #########################################################
  ## PHPMYADMIN ###########################################
  #########################################################
  phpmyadmin:
    image: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    #restart: always
    ports:
     - 8074:80
    networks: 
     - internal-net
     - external-net
    volumes:
     - /sessions

networks:
  external-net:
  internal-net:
    internal: true

volumes:
  db_test_vol: 
