version: "3.4"

services:
  ########################################################
  # FRONTEND #############################################
  ########################################################
  frontend:
    image: gradido/frontend:development
    build:
      target: development
    environment:
      - NODE_ENV="development"
      # - DEBUG=true
      - NUXT_BUILD=/tmp/nuxt # avoid file permission issues when `rm -rf .nuxt/`
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      - frontend_node_modules:/app/node_modules
      # bind the local folder to the docker to allow live reload
      - ./frontend:/app

  #########################################################
  ## LOGIN SERVER #########################################
  #########################################################
  login-server:
    build:
      target: login_server_debug
      dockerfile: Dockerfile.debug
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./logs:/var/log/grd_login 
      - ./login_server/src:/code/src 
      - login_build:/code/build_vol
      
  #########################################################
  ## NGINX ################################################
  #########################################################
  nginx:
    volumes: 
      - ./logs:/var/log/nginx 
  
  #########################################################
  ## PHPMYADMIN ###########################################
  #########################################################
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    #restart: always
    ports:
     - 8074:80
    networks: 
     - internal-net
     - external-net
    volumes:
     - /sessions
   
volumes:
  frontend_node_modules:
  login_build:

