name: on-push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: git submodule update --init --recursive
        run: docker-compose up -d
      - name: Test
        env:
          GN_INSTANCE_FOLDER: /tmp/gradio-node-instance
          GN_CONTAINER_NAME: gradido-node-build
        run: docker run gradido-node-test
        timeout-minutes: 2

